baseurl: ""

markdown: kramdown
plugins:
  - jekyll-email-protect

timezone: Asia/Shanghai

collections:
  - publications
  - news
  - showcase
  - posts


exclude:
  - vendor
  - README.md
  - Gemfile
  - Gemfile.lock
